// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy-OYHIOHadex-JX6pAMARV9EGBotTawk',
    appId: '1:356784483498:web:8e5e1f08c0be1bff33f4d3',
    messagingSenderId: '356784483498',
    projectId: 'sparrowshop-ed353',
    authDomain: 'sparrowshop-ed353.firebaseapp.com',
    storageBucket: 'sparrowshop-ed353.appspot.com',
    measurementId: 'G-PK8XJEV10S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyo951L1VvhCmZtbFfPdsA1d7GJXyonKE',
    appId: '1:356784483498:android:a8a35a67c5cba7cb33f4d3',
    messagingSenderId: '356784483498',
    projectId: 'sparrowshop-ed353',
    storageBucket: 'sparrowshop-ed353.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGU1K_D27vTsnANVnG0kyz8ZlmufJP0V4',
    appId: '1:356784483498:ios:92019adc0b86378c33f4d3',
    messagingSenderId: '356784483498',
    projectId: 'sparrowshop-ed353',
    storageBucket: 'sparrowshop-ed353.appspot.com',
    iosClientId: '356784483498-dkosj7ugtjnj5ggkh13qgm09r48iqk3d.apps.googleusercontent.com',
    iosBundleId: 'com.sparrowTech.sparrowShop',
  );
}
